---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: cluster-02
  namespace: management-system
  annotations:
    cnrm.cloud.google.com/project-id: devops-melb-24-436709
spec:
  enableAutopilot: true
  location: australia-southeast2
  releaseChannel:
    channel: RAPID
  workloadIdentityConfig:
    workloadPool: devops-melb-24-436709.svc.id.goog
  nodeConfig:
    diskSizeGb: 50
    imageType: COS_CONTAINERD
    machineType: e2-standard-8
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubMembership
metadata:
  name: cluster-02
  namespace: management-system
  annotations:
    cnrm.cloud.google.com/project-id: devops-melb-24-436709
spec:
  location: global
  authority:
    # Issuer must contain a link to a valid JWT issuer. Your ContainerCluster is one. To use it, replace ${PROJECT_ID?} with your project ID.
    issuer: https://container.googleapis.com/v1/projects/devops-melb-24-436709/locations/australia-southeast2/clusters/cluster-02
  endpoint:
    gkeCluster:
      resourceRef:
        name: cluster-02
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeature
metadata:
  name: cluster-02
  namespace: management-system
  annotations:
    cnrm.cloud.google.com/project-id: devops-melb-24-436709
spec:
  location: global
  # The resourceID must be "multiclusteringress" if you want to use multi-cluster
  # ingress feature.
  resourceID: multiclusteringress
  spec:
    multiclusteringress:
      configMembershipRef:
        name: cluster-01
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: cluster-02
  namespace: flux-system
spec:
  summary: "cluster-02"
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: "cluster-02"
      namespace: flux-system
  providerRef:
    name: flux-system-dispatch
  eventMetadata:
    project: "devops-melb-24-436709"
    cluster: "cluster-02"
    location: "australia-southeast2"
