---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: cluster-02
  namespace: management-system
  annotations:
    cnrm.cloud.google.com/project-id: devops-melb-24-436709
    cnrm.cloud.google.com/remove-default-node-pool: "true"
spec:
  location: australia-southeast2
  minMasterVersion: "1.30.3-gke.1969001"
  gatewayApiConfig:
    channel: "CHANNEL_STANDARD"
  initialNodeCount: 1
  releaseChannel:
    channel: "REGULAR"
  subnetworkRef:
    external: "projects/devops-melb-24-436709/regions/australia-southeast2/subnetworks/nodes-australia-southeast2"
  networkRef:
    external: "projects/devops-melb-24-436709/global/networks/gitops-gke-clusters"
  workloadIdentityConfig:
    identityNamespace: "devops-melb-24-436709.svc.id.goog"
  datapathProvider: "ADVANCED_DATAPATH"
---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: cluster-02-nodepool
  namespace: management-system
spec:
  clusterRef:
    name: cluster-02
  location: australia-southeast2
  autoscaling:
    minNodeCount: 1
    maxNodeCount: 3
  management:
    autoRepair: true
    autoUpgrade: true # TODO
  nodeConfig:
    machineType: "e2-standard-8"
    spot: true
    diskSizeGb: 50
    oauthScopes:
      - "https://www.googleapis.com/auth/logging.write"
      - "https://www.googleapis.com/auth/monitoring"
      - "https://www.googleapis.com/auth/devstorage.read_write"
  upgradeSettings:
    maxSurge: 1
    maxUnavailable: 1
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubMembership
metadata:
  name: cluster-02
  namespace: management-system
  annotations:
    cnrm.cloud.google.com/project-id: devops-melb-24-436709
spec:
  location: global
  authority:
    # Issuer must contain a link to a valid JWT issuer. Your ContainerCluster is one. To use it, replace ${PROJECT_ID?} with your project ID.
    issuer: https://container.googleapis.com/v1/projects/devops-melb-24-436709/locations/australia-southeast2/clusters/cluster-02
  endpoint:
    gkeCluster:
      resourceRef:
        name: cluster-02
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeature
metadata:
  name: cluster-02
  namespace: management-system
  annotations:
    cnrm.cloud.google.com/project-id: devops-melb-24-436709
spec:
  location: global
  # The resourceID must be "multiclusteringress" if you want to use Multi Cluster Gateway API
  # https://cloud.google.com/kubernetes-engine/docs/how-to/enabling-multi-cluster-gateways#enable_multi-cluster_services
  resourceID: multiclusteringress
  spec:
    multiclusteringress:
      configMembershipRef:
        name: cluster-02
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: cluster-02
  namespace: flux-system
spec:
  summary: "cluster-02"
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: "cluster-02"
      namespace: flux-system
  providerRef:
    name: flux-system-dispatch
  eventMetadata:
    project: "devops-melb-24-436709"
    cluster: "cluster-02"
    location: "australia-southeast2"
