---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wli-github-federation
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 10m
  path: "kubernetes/namespaces/base/management-system/config/oidc"
  prune: true
  wait: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: kcc-controller
      namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
