---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: whereami
  namespace: team-alpha-tenant
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: "./apps/base/demo/whereami"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: tenant-alpha-repo
    namespace: flux-system
