---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: whereami
  namespace: team-bravo-tenant
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: "./apps/base/demo-2/whereami"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: tenant-bravo-repo
    namespace: flux-system
