apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

patches:
  - target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux
    path: ../../patches/deployment.yaml
