---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: team-bravo
  name: team-bravo-tenant
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: team-bravo
  name: team-bravo
  namespace: team-bravo-tenant
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: team-bravo
  name: team-bravo-reconciler
  namespace: team-bravo-tenant
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:team-bravo-tenant:reconciler
- kind: ServiceAccount
  name: team-bravo
  namespace: team-bravo-tenant
