apiVersion: v1
data:
    token: ENC[AES256_GCM,data:UOgBhO42B5jZOa9FTQdJo0gFl/Aq+Rc4ODYevqc7vXuVNLxgmUS+CHveuYFwAwBIgGzTBy3CpktQeTpzRqmWoOsER7fRP90YfLyDx+MARksP+fYkF7qSbAuJS7559rbUZxK42w6y59DDgzc8gtU+uuyR5zVXG7bSzYNkew==,iv:lrbRzUXbLxZt9ccQPEktQJ21qrBx3KYcYFIW7ytGXMU=,tag:ClGAbq0f6y6nvrF73D3wOw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: github-token
    namespace: flux-system
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/atomic-gke-clusters/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2024-10-04T22:54:10Z"
          enc: CiQAeELGV8f7yin2//WR26u1545YmxFW0MKCUzlfTHoH4nFp/k8SSQBFjqVm00HPkKSGK3FaMcmMAy27nrmJP7ptZ0PUw5YdBIPxGLx+570KG+ikNjSf7A4hM8/M8IEoTZhT4/NwRPvaZJt7Vggru1k=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-10-04T22:54:11Z"
    mac: ENC[AES256_GCM,data:1PVjzmDfrRXghXYsD1WLbbXLZcDczGliZ+EXUBNscwFmwECNTEul1VBzQYexXMwlTM7dsUOlwdkiEqY+M7FyWVqnT1Mx+7hVUcsq6xzhkx7Em3uQHerUeVjN9ccaNfD6pnGA5ZGMKFUbr27m8qE9UNhdOzMIJeodEk2hqLZNZm0=,iv:ZWoCvGVa+QyZN+Gg0s3mLCxoK2/FveSapizJ5iRqxeg=,tag:oZjYeWR99GrNHFsivYChYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
