apiVersion: v1
data:
    token: ENC[AES256_GCM,data:IgX6O+8SS4FJDpOEzq/N4FNTsviZ/H+8rwcxfXW5RSaa9o+NVlU+sG7qhNiSbwTCBROr0rGPcgAltQg4Fv0lsxcp5eJYFSlAU1rqtSBbGzF0GHOE1a5SwDcsQSsENPELPoBUOk8/+3q7qvE5y0XGiXatHfmHmGm8N9cAhg==,iv:fovkCSHOUa/jadQ1Eioqah6pBxwebFEyO3RTS53P2rE=,tag:JYPltNdu7CJ8OJufyBWCJg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: github-token
    namespace: flux-system
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/devops-melb-24-436709/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2024-10-05T03:31:26Z"
          enc: CiQAXAyDBMRBGImZyBg1FtVeue4he4oH7qK0pxVCPqonLpoLvy4SSAA4+800av9Q2FR2T25WZjacWnM1gyzdpdZMyKyP9dbA235IuKpBqhbaWIK8eq33oyI5N8s/qKYVgqsaJDaUAH7S4J+8CMzcwg==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-10-05T03:31:28Z"
    mac: ENC[AES256_GCM,data:lhOpusRfmt7pUIVcB26g/R/0nab22OwqiLNrcINDn+TrR+QpO5vqpr+uH28DFXGseiCxCjA2GceOmoKOKuiAKkjFx/LKjucECe1jW0rzSHF9ea0r6/WgKPr+9zFheyvyFTh0HkYwaA5f6aaSU8rwhqs7VIWCXYdZcXiecQPGoOg=,iv:5KaoRVV46vXzAuguihNwCk9KpSMSEa+Xf7FG0rEC9Pw=,tag:nP3axwdmprAnic1B7P+ROQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
